In [3]:
import numpy as np

In [2]:
test_array = np.array(["1","4",5,8],float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [5]:
test_array = np.array([1,4,5,"8"],float)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array[3])

numpy.float64

In [7]:
test_array.dtype

dtype('float64')

In [8]:
np.array([[1, 4, 5, "8"]], np.float32).shape

(1, 4)

In [17]:
test_array.shape

(4,)

In [20]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [23]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [7]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 4, 4)

In [28]:
np.array(tensor, int).ndim

3

In [29]:
np.array(tensor, int).size

64

RESHAPE

In [9]:
np.array(tensor).reshape(16,4)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])