In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :",n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [4]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [5]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


In [6]:
data = [[3,5,20],[10,5,50],[1,5,10]]
x_data = torch.tensor(data)

In [7]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [8]:
x_data[:2,1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [9]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [12]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [13]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [14]:
x_data.shape

torch.Size([3, 3])

In [16]:
x_data.dtype

torch.int64

In [17]:
x_data.device

device(type='cpu')