In [1]:
import numpy as np

In [2]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [4]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [5]:
test.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [6]:
test.shape

(8,)

In [7]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [7]:
# indexing
test_list = [[1, 2, 5, 8], 
             [2, 3, 6, 9], 
             [3, 4, 7, 10]] # 3 x 4 array
test_array = np.array(test_list, int)

print(test_array[1][2]) # 6 출력
print(test_array[1, 2]) # 동일하게 6 출력

# slicing Start:End:Interval의 문법
print(test_array[1:2, :2]) # 1번행 이상 / 2번행 미만, 2번 열 미만 출력
print(test_array[1, :2]) # 동일하게 출력되지만, 위에는 2차원, 이 코드는 1차원으로 출력

print(test_array[:, 2:]) # 모든 행, 2번 열 이후 출력

print(test_array[:, ::2]) # 모든 행 + 모든 열을 2칸씩 띄워서

print(test_array[1::2, 0:4:3]) # 1번 행부터 끝까지, 2행씩 띄워서 출력

6
6
[[2 3]]
[2 3]
[[ 5  8]
 [ 6  9]
 [ 7 10]]
[[1 5]
 [2 6]
 [3 7]]
[[2 9]]
