In [1]:
import numpy as np

In [2]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_example[0][0]

1

In [4]:
test_example[1][0]

4

slicing

In [9]:
test_example = np.array([
    [0,2,5,8], [1,2,5,8],[8,4,2,5],[1,2,5,8]], int)
test_example[:2,:]

array([[0, 2, 5, 8],
       [1, 2, 5, 8]])

In [10]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [4, 2],
       [2, 5]])

In [11]:
test_example[1,:2]

array([1, 2])

In [13]:
test_example[:,1:3] 
test_example[1,:2] 

array([1, 2])

In [14]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [18]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])