In [1]:
import torch

In [2]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.5344, 0.8329],
         [0.4564, 0.0467],
         [0.3958, 0.2340]],

        [[0.8713, 0.9667],
         [0.0092, 0.6175],
         [0.7378, 0.7336]]])

In [3]:
tensor_ex.view([-1,6])

tensor([[0.5344, 0.8329, 0.4564, 0.0467, 0.3958, 0.2340],
        [0.8713, 0.9667, 0.0092, 0.6175, 0.7378, 0.7336]])

In [4]:
tensor_ex.reshape([-1,6])

tensor([[0.5344, 0.8329, 0.4564, 0.0467, 0.3958, 0.2340],
        [0.8713, 0.9667, 0.0092, 0.6175, 0.7378, 0.7336]])

In [5]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
a = torch.zeros(3,2)

b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [12]:
import numpy as np
n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)

In [13]:
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [15]:
t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [16]:
t1 -t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [17]:
t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [18]:
t1 +10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [19]:
t1 + n1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]], dtype=torch.float64)

In [21]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

In [22]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [23]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [24]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [25]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.7063, 0.9164],
        [0.4102, 0.8036],
        [0.7991, 0.5012],
        [1.1382, 0.4706],
        [0.7544, 0.9430]])

In [26]:
w = torch.tensor(2.0,requires_grad=True)
y = w**2
z = 10*y+25
z.backward()
w.grad

tensor(40.)

In [27]:
  a = torch.tensor([2.,3.],requires_grad =True)
  b = torch.tensor([6.,4.],requires_grad =True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)
a.grad

tensor([36., 81.])

In [28]:
b.grad

tensor([-12.,  -8.])